

volumes:
  database:

networks:
  backend:

services:
  backend:
    build: ./backend
    container_name: backend_camagru
    env_file: .env
    hostname: backend
    ports:
      - 7500:5000
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:16beta1-alpine3.18
    container_name: postgres_camagru
    hostname: postgres
    env_file: .env
    restart: always
    ports:
      - 7501:5432
    volumes:
      - database:/var/lib/postgresql/data/
    networks:
      - backend

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer_camagru
    env_file: .env
    restart: always
    ports:
      - 7502:8080
    networks:
      - backend

  nginx:
    build: ./frontend
    container_name: nginx_camagru
    env_file: .env
    depends_on: 
      - backend
    ports:
      - 7505:80
    restart: always
    networks:
      - backend
    volumes:
      - ./frontend:/app

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_camagru
    env_file: .env
    ports:
      - 7506:8080
    restart: always
    networks:
      - backend

  # mail:
  #   image: marcopas/docker-mailslurp
  #   container_name: mail_cm3000

