import smtplib

# Import the email modules we'll need
from email.message import EmailMessage

from app import app


@app.route('/send_mail')
def send_mail():
    import smtplib
    from email.mime.text import MIMEText

    # Configuration
    port = 587
    smtp_server = "live.smtp.mailtrap.io"
    login = "1738072774"  # Your login generated by Mailtrap
    password = "1527385e4330a35a7e12b10ef1f1f4aa"  # Your password generated by Mailtrap

    sender_email = "mailtrap@demomailtrap.com"
    receiver_email = "kalityoflife@gmail.com"

    # Plain text content
    text = """\
    Hi,
    Check out the new post on the Mailtrap blog:
    SMTP Server for Testing: Cloud-based or Local?
    https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/
    Feel free to let us know what content would be useful for you!
    """

    # Create MIMEText object
    message = MIMEText(text, "plain")
    message["Subject"] = "Plain text email"
    message["From"] = sender_email
    message["To"] = receiver_email

    # Send the email
    with smtplib.SMTP(smtp_server, port) as server:
        server.starttls()  # Secure the connection
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message.as_string())

    print('Sent')